name: Build LaTeX document
on:
    push:
        branches:
            - source
    workflow_dispatch:
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compile LaTeX document
              uses: dante-ev/latex-action@latest
              with:
                  root_file: main.tex
                  compiler: lualatex
                  args: -interaction=nonstopmode -shell-escape
            - name: Gather build artifacts
              run: |
                  mkdir build
                  mv *.pdf build/
                  mv web/* build/
                  mv README.md build/

            - name: Publish to GitHub pages
              if: success() && github.ref == 'refs/heads/source'
              uses: crazy-max/ghaction-github-pages@v1
              with:
                  target_branch: gh-pages
                  build_dir: build/
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
