name: Build LaTeX document
on:
    push:
        branches:
            - source
        paths:
            - "*.tex"
    workflow_dispatch:
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git repository
              uses: actions/checkout@v2
            - name: Compile LaTeX document
              uses: dante-ev/latex-action@latest
              with:
                  root_file: main.tex
                  compiler: lualatex
                  args: -interaction=nonstopmode -shell-escape
            - name: Create PNG from PDFs
              uses: jruipinto/ImageMagick-action@v1
              with:
                  command: mogrify -verbose -density 500 -resize 800 -opaque white -format png ./*.pdf
            - name: Create image for readme
              uses: jruipinto/ImageMagick-action@v1
              with:
                  command: convert main.png -background white -alpha remove -alpha off demo.png
            - name: Add & Commit demo.png
              uses: EndBug/add-and-commit@v7.1.1
              with:
                  add: demo.png
                  message: Update demo.png
                  signoff: true
            - name: Gather build artifacts
              run: |
                  mkdir build
                  cp -r *.pdf build/
                  cp -r *.png build/
            - name: Publish to GitHub pages
              if: success() && github.ref == 'refs/heads/source'
              uses: crazy-max/ghaction-github-pages@v2.3.0
              with:
                  target_branch: gh-pages
                  build_dir: build/
                  keep_history: true
                  commit_message: Deploy to GitHub pages ${{ github.sha }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
